#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  # Refuse to write a real secret into a TRACKED file (2026-08-19 tribunal, security 13):
  # ENV_FILE defaults to ./.env in the project repo, and secret-handling.md names "writing a
  # secret to a tracked file" a BLOCK. If we are inside a work tree and git does NOT ignore
  # ENV_FILE, stop before the value lands — the next commit would leak it.
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && ! git check-ignore -q "$ENV_FILE" 2>/dev/null; then
    printf '  %s✗ REFUSED%s %s is NOT gitignored — a real value here would be committed. Add it to .gitignore first (echo "%s" >> .gitignore), then re-run.\n' \
      "${RED:-}" "${RESET:-}" "$ENV_FILE" "$ENV_FILE" >&2
    return 1
  fi
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# 1Password-first secret provisioning (house rule: ~/.claude/rules/secret-handling.md)
# A secret never transits the terminal, the transcript, or shell history when
# 1Password can carry it. ask_secret is the FALLBACK, not the default.
# ──────────────────────────────────────────────────────────────────────────

OP_VAULT="${OP_VAULT:-OnlyDans}"     # placeholders default to the business vault (three-lane table:
                                    # ~/.claude/references/secret-injection-protocol.md § Which vault)
OP_SA="${OP_SA:-onlydans}"          # service account = basename of ~/.config/op/<account>.token —
                                    # it MUST be an account that sees $OP_VAULT (set both when you
                                    # change either; `op-sa.sh <account> vault list` shows the reach)

# _op — every 1Password call goes through the OS's op-sa.sh when it is installed (headless: WSL
# cannot reach the desktop app, so an exported service-account token is the ONLY session there —
# which is why generated wizards used to hand-roll env-file loaders). Without the wrapper it falls
# back to bare `op` (the desktop-app signin = the FULL human account, strictly broader than any
# service account) — announced once, and only for an interactive run: a headless caller with no
# wrapper fails closed instead of silently switching principals (security seat 2026-09-02).
_op() {
  if [ -f "$HOME/.config/op/op-sa.sh" ]; then bash "$HOME/.config/op/op-sa.sh" "$OP_SA" "$@"; return; fi
  [ -t 0 ] || { echo "op: no ~/.config/op/op-sa.sh and no TTY — refusing to fall back to the desktop-app session headlessly" >&2; return 1; }
  [ -n "${_OP_FALLBACK_SAID:-}" ] || { echo "note: op-sa.sh not installed — using the interactive 1Password session (your full account, not a service account)" >&2; _OP_FALLBACK_SAID=1; }
  op "$@"
}
# _op_ready — true when the op CLI is present and a session (wrapper or signin) is usable.
_op_ready() { command -v op >/dev/null 2>&1 && _op whoami >/dev/null; }   # stderr stays visible: the one-time fallback note must not be swallowed here

# op_placeholder ITEM [FIELD] — create a PASTE-ME placeholder in 1Password so
# the human pastes the real value in the 1Password UI, never into this terminal.
# Idempotent: an existing item is left untouched.
op_placeholder() {
  local item="$1" field="${2:-credential}"
  if ! _op_ready; then
    SKIPPED+=("1Password item '$item' (op unavailable — create it by hand)")
    warn "op unavailable — create '$item' in 1Password manually"
    return 1
  fi
  if _op item get "$item" --vault "$OP_VAULT" >/dev/null 2>&1; then
    note "1Password item '$item' already exists — leaving it alone"
  else
    _op item create --category="API Credential" --title="$item" \
      --vault "$OP_VAULT" "$field=PASTE-ME" >/dev/null
    printf '  %s✓ created%s 1Password placeholder %s\n' "$GREEN" "$RESET" "$item"
  fi
  say "Open 1Password → $OP_VAULT → '$item' and paste the real value into '$field'."
  pause "Done pasting? Press Enter."
}

# op_env KEY "op://vault/item/field" — read the secret from 1Password straight
# into ENV_FILE. The value never reaches stdout, the transcript, or history.
op_env() {
  local key="$1" ref="$2" value
  if ! _op_ready; then
    SKIPPED+=("$key from $ref (op unavailable)")
    warn "op unavailable — $key not written"
    return 1
  fi
  if ! value=$(_op read "$ref"); then
    SKIPPED+=("$key from $ref (op read failed)")
    warn "could not read $ref — check the value was pasted"
    return 1
  fi
  if [[ "$value" == "PASTE-ME" || -z "$value" ]]; then
    SKIPPED+=("$key from $ref (still the placeholder)")
    warn "$ref is still PASTE-ME — paste the real value, then re-run"
    return 1
  fi
  write_env "$key" "$value"
  printf '  %s✓ verified%s %s (%s chars, never printed)\n' "$GREEN" "$RESET" "$key" "${#value}"
}

# op_secret NAME "op://vault/item/field" — pipe a 1Password secret into a
# GitHub Actions secret over stdin. No intermediate variable, no echo, no argv.
op_secret() {
  local name="$1" ref="$2"
  if ! _op_ready; then SKIPPED+=("GitHub secret $name (op unavailable)"); return 1; fi
  if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
    SKIPPED+=("GitHub secret $name (gh not ready)"); warn "gh not ready — $name not set"; return 1
  fi
  if _op read "$ref" | gh secret set "$name"; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s from 1Password\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("GitHub secret $name (op to gh pipe failed)")
    warn "could not set $name from $ref"
  fi
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "Example setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe — API keys"
say "We'll capture your Stripe test keys for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"

# Public value: a plain ask is fine — it is not a secret.
step "Copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"

# Secret value: 1Password-first — the human pastes into 1Password, not here.
step "Click 'Reveal test key' on the Secret key row and copy it."
op_placeholder "Stripe test secret key" credential
op_env    STRIPE_SECRET_KEY "op://$OP_VAULT/Stripe test secret key/credential"
op_secret STRIPE_SECRET_KEY "op://$OP_VAULT/Stripe test secret key/credential"

# FALLBACK only — where the project has no 1Password integration, swap the
# three lines above for ask_secret + write_env + set_secret (hidden entry).
# ──────────────────────────────────────────────────────────────────────────

finish
